### ISSUE TITLE
AV1 support?

### ISSUE THREAD

**Issue by GodBleak** [mmomtchev/ffmpeg#83]
It seems I'm unable to encode using AV1, I tried with this:
```ts
const videoOutput = new VideoEncoder({
  type: "Video",
  codec: ffmpeg.AV_CODEC_AV1,
  bitRate: 2.5e6,
  width: videoDefinition.width,
  height: videoDefinition.height,
  frameRate: new ffmpeg.Rational(25, 1),
  pixelFormat: videoDefinition.pixelFormat,
});
```
Which results in:

```
checkCodec: Encoding context, but codec does not support encoding
```
I gather that the library isn't using the system `ffmpeg` as the one installed does support it:

```zsh
❯ ffmpeg -codecs
ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
...
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ..D... = Data codec
 ..T... = Attachment codec
 ...I.. = Intra frame-only codec
 ....L. = Lossy compression
 .....S = Lossless compression
 -------
...
 DEV.L. av1                  Alliance for Open Media AV1 (decoders: libdav1d libaom-av1 av1 av1_cuvid av1_qsv) (encoders: libaom-av1 librav1e libsvtav1 av1_nvenc av1_qsv av1_amf av1_vaapi)
 ```
 
Is there a way I can enable AV1 support? I've tried looking through the library to find anything to configure ffmpeg, but I couldn't find anything.

**Comment by mmomtchev** [comment]
As you have surely seen from my profile page, I am currently in a middle of a huge extortion involving the French police, corrupt judges, several big tech companies and many major open source projects. In order to intimidate me, people are posting simultaneously in my projects.

**Comment by GodBleak** [comment]
I have not. Are you saying the project is unmaintained?

**Comment by mmomtchev** [comment]
It is. And you, are you saying you are taking part in the extortion with the police and the dicks?

**Comment by GodBleak** [comment]
No, extortion uses threats to obtain something, usually money. I don't want your money. I just want to know how I can use your project to encode AV1, and I'm not threatening you to tell me, if you don't want to for some reason, I'll just use H265, I guess.

**Comment by mmomtchev** [comment]
No, extortion can be about many things - and in this case it is to stop talking about this affair.

I am getting other simultaneous comments with everything you post, so I can make a pretty safe bet that H265 is the last thing on your mind.

**Comment by GodBleak** [comment]
Please link these other simultaneous comments, I'd be interested to know if my account has somehow been compromised. Like I said, I just want to encode using AV1.

I read your profile, and as you can see from 

- jellyfin/jellyfin/issues/10621
- jellyfin/jellyfin/issues/10421
- jellyfin/jellyfin-web/issues/4076
- [GodBleak/pub/restream](https://gitlab.godbleak.dev/pub/restream)

my interest in media servers seems to predate your affair. My inquiry is pretty on-brand for my interests and the work I do. It also further underscores that codecs (including H265 (and how much I'd prefer to use AV1)) are pretty high up there on the list of things on my mind. 

I also don't see how providing instructions on how I can use this library to encode with AV1 would further any nefarious goal I had. You're already providing instructions in the readme, I'm not asking you to do anything you haven't already demonstrated you're willing to do. However, I respect that refusing to do so is your prerogative. 

Please don't forget to link those simultaneous comments, as I want to ensure I'm not being impersonated.

**Comment by mmomtchev** [comment]
Certainly.

Most places where those things happened are genuine projects.

It is just that the reason for what you are asking is to check whether I would accept to work while for you while you sent me simultaneous messages with other people involved in this affair.

**Comment by GodBleak** [comment]
I'm still waiting to see these simultaneous comments (or messages). Without them, your whole accusation is baseless. That's ignoring the fact the even if the accusation had merit, it's irrelevant to the issue.

**Comment by GodBleak** [comment]
Actually, having looked at the other issues and pull requests related to your projects, it's clear that they're not fit for use in production. Thank you for making this project open source; I'll fork it, figure this out myself, and republish it. 

I say this out of genuine concern for your well-being, not as a jab, I hope you can find the help you require.

**Comment by mmomtchev** [comment]
I try to hit back accordingly as the other were less cocky then you.

Besides, this whole conservation, if you go back and read it from the beginning, is probably more then enough to convince everyone else what is going on.

I never expected you to admit whatever.

I am simply absolutely amazed that someone can have the nerve to show me that he is part of an extortion, and then to ask for a feature, and to do so by a "do you still beat you wife" approach.
